import math


print "// THESE CONSTANTS ARE AUTOMATICALLY GENERATED"
print "// DO NOT EDIT THIS FILE DIRECTLY (CHANGES MAY GET ACCIDENTALLY WIPED)"
print ""
print ""
print "JSTerrain.chunkConstants = ["

class Chunk():
    def __init__(self, level, size, x, y, quad, border_edge_n, border_edge_e, border_edge_s, border_edge_w, variable_lod_edge_n, variable_lod_edge_e, variable_lod_edge_s, variable_lod_edge_w):
        self.level = level
        self.size = size
        self.x = x
        self.y = y
        self.minx = self.x * self.size
        self.miny = self.y * self.size
        self.maxx = self.minx + self.size
        self.maxy = self.miny + self.size
        self.quad = quad
        self.vb = 0
        if quad == 1 or quad == 2:
            self.vb = 1
        if quad == 3 or quad == 4:
            self.vb = 2
        self.border_edge_n = border_edge_n
        self.border_edge_e = border_edge_e
        self.border_edge_s = border_edge_s
        self.border_edge_w = border_edge_w
        self.variable_lod_edge_n = variable_lod_edge_n
        self.variable_lod_edge_e = variable_lod_edge_e
        self.variable_lod_edge_s = variable_lod_edge_s
        self.variable_lod_edge_w = variable_lod_edge_w
        
    def get_border_edge_string(self):
        number = 0
        if self.border_edge_n:
            number = number + 1
        if self.border_edge_e:
            number = number + 2
        if self.border_edge_s:
            number = number + 4
        if self.border_edge_w:
            number = number + 8
        return str(number)
        
    def get_variable_lod_edge_string(self):
        number = 0
        if self.variable_lod_edge_n:
            number = number + 1
        if self.variable_lod_edge_e:
            number = number + 2
        if self.variable_lod_edge_s:
            number = number + 4
        if self.variable_lod_edge_w:
            number = number + 8
        return str(number)
        
    def get_index_count(self):
        return 16 * 16 * 6
        
    def get_indices(self):
        indices = ""
        for x in range(0, 16):
            for y in range(0, 16):
                if self.level == 4:
                    indices = "".join([indices, "0,0,0,0,0,0,"])
                else:
                    quadsize = self.size / 16
                    px = x * quadsize + self.minx
                    py = y * quadsize + self.miny
                    
                    if self.vb == 2:
                        py = py - 128
                        
                    a = (py * 257) + px
                    b = a + quadsize
                    c = a + 257 * quadsize
                    d = c + quadsize
                    
                    indices = "".join([indices, str(a), ",", str(b), ",", str(c), ",", str(c), ",", str(b), ",", str(d), ","])
        return indices
        
    def to_string(self):
        return "".join(["{level:", str(self.level), ",size:", str(self.size), ",position:{x:", str(self.x), ",y:", str(self.y), "},min:{x:", str(self.minx), ",y:", str(self.miny), "},max:{x:", str(self.maxx), ",y:", str(self.maxy), "},centre:{x:", str(self.minx + self.size / 2), ",y:", str(self.miny + self.size / 2), "},quad:" + str(self.quad) + ",vb:" + str(self.vb) + ",startIndex:" + str(self.start_index) + ",borderEdges:", self.get_border_edge_string(), ",variableLodEdges:", self.get_variable_lod_edge_string(), "},"])
        #return "".join(["JSTerrain.ChunkConstant(", str(self.level), ",", str(self.size), ",", str(self.x), ",", str(self.y), ",", str(self.minx), ",", str(self.miny), ",", str(self.maxx), ",", str(self.maxy), ",", str(self.minx + self.size / 2), ",", str(self.miny + self.size / 2), "," + str(self.quad) + "," + str(self.vb) + "," + str(self.start_index) + ",", self.get_border_edge_string(), ",", self.get_variable_lod_edge_string(), "),"])
        
chunklist = []

for chunk in range(0, 1 + 4 + 16 + 64 + 256):
    chunklist.append(Chunk(0, 0, 0, 0, 0, False, False, False, False, False, False, False, False))
    
def recurse(chunk_id, level, size, x, y, quad, corner, border_n, border_e, border_s, border_w):
    if corner == -1:
        chunklist[chunk_id] = Chunk(level, size, x, y, quad, border_n, border_e, border_s, border_w, True, True, True, True)
    else:
        chunklist[chunk_id] = Chunk(level, size, x, y, quad, border_n, border_e, border_s, border_w, False, False, False, False)
        if corner == 0:
            chunklist[chunk_id].variable_lod_edge_n = True
            chunklist[chunk_id].variable_lod_edge_w = True
        elif corner == 1:
            chunklist[chunk_id].variable_lod_edge_n = True
            chunklist[chunk_id].variable_lod_edge_e = True
        elif corner == 2:
            chunklist[chunk_id].variable_lod_edge_s = True
            chunklist[chunk_id].variable_lod_edge_w = True
        elif corner == 3:
            chunklist[chunk_id].variable_lod_edge_s = True
            chunklist[chunk_id].variable_lod_edge_e = True
    if level != 0:
        recurse(chunk_id * 4 + 1, level - 1, size / 2, x * 2, y * 2, 1 if quad == 0 else quad, 0, border_n, False, False, border_w)
        recurse(chunk_id * 4 + 2, level - 1, size / 2, x * 2 + 1, y * 2, 2 if quad == 0 else quad, 1, border_n, border_e, False, False)
        recurse(chunk_id * 4 + 3, level - 1, size / 2, x * 2, y * 2 + 1, 3 if quad == 0 else quad, 2, False, False, border_s, border_w)
        recurse(chunk_id * 4 + 4, level - 1, size / 2, x * 2 + 1, y * 2 + 1, 4 if quad == 0 else quad, 3, False, border_e, border_s, False)
        
recurse(0, 4, 256, 0, 0, 0, -1, True, True, True, True)

start_index = 0
for chunk in chunklist:
    chunk.start_index = start_index
    start_index = start_index + chunk.get_index_count()
    print "".join(["\t", chunk.to_string()])
    
print "];"
print ""
print ""
print "JSTerrain.LODSize = [16, 32, 64, 128, 256];"
print ""
print ""
print "JSTerrain.indices = new Uint16Array([",
for x in range(0, 16):
    for y in range(0, 16):
        a = (y * 17) + x
        b = a + 1
        c = a + 17
        d = c + 1
        print str(a) + "," + str(b) + "," + str(c) + "," + str(c) + ",", str(b) + "," + str(d) + ",",
print "]);"


